Automap.cs

When an UNDO is performed, the resulting room name is printed, followed
by "[Previous turn undone.]" I added simple code to ignore this line
when processing paragraphs, which makes this room look like one with a
non-verbose description. It's not perfect (for that, you'd have to store
a state graph), but it should handle most cases.

Handle undo with automapping.

---

Docs/index.shtml
Docs/style.css

This should fix the issue about ">SEE" and ">REGION" being hard to find. Also formatted tables but still need to format body text (provide margins). Maybe next commit.

add more css info and automap detail

---

Canvas.cs
Element.cs
MainForm.cs
Project.cs
Room.cs
RoomExtensions.cs
Trizbort.csproj

Probably those catch(Exception) statements should be made more specific, but for now this should eliminate the 14 build warnings we see.

Eliminate pesky build warnings.

---

Export/ZilExporter.cs

- Update main loop so M-END doesn't run for meta verbs.
- Escape contents of strings.
- Export history (creating an ABOUT verb).
- Don't write empty room descriptions.
- Use a PER routine for conditional exits.
- Set object SYNONYM and ADJECTIVE separately.
- Fix spacing/style nits.

Tweak the ZIL exporter

---

Canvas.Designer.cs
Canvas.cs
MainForm.Designer.cs
MainForm.cs
Room.cs
RoomPropertiesDialog.Designer.cs
RoomPropertiesDialog.cs

I noticed I took code out to test a few things with the flicker for the previous merge, to make sure things worked a certain way, but I forgot to put the line back in. #145 is the issue.
I have added octagonal shapes. I cut the vertical/horizontal sides to half the actual length, but this can be changed in the quarterPoint function. Which might need to be renamed. (WeightPoint?) I made sure that first-room highlighting and select highlighting works, and both the context and pull-down menus should show the option.

#89 and a tweak to the flicker

---

Settings.cs

I found this when I opened a project, changed the start room color, and closed it. Trizbort doesn't see color changes as changes in the pronect.
Given that this code is so close to other lines marking the project as dirty, I am vaguely worried Genstein had a reason not to mark some changes as worth saving. But I think I've had trizbort "forget" other color change saves when that's all I do & from a user perspective, I think this should be there.

Mark project dirty if colors in Color tab changed

---

AppSettingsDialog.Designer.cs
AppSettingsDialog.cs
Canvas.cs
Export/Inform7Exporter.cs
Room.cs
RoomPropertiesDialog.cs
Settings.cs

I also made a change to the "about" code. We needed to throw in a [line break], and with the code being arranged by books, etc., we needed to throw in a WriteLine, which I think made the code look a bit nicer anyway.
I want to make it so there is 1 line of space between suitably different lines of code e.g.
part TilesIslet
There is a room called TilesIslet. The printed name of it is "Tiles/Islet". It is in Resort.
A Rock is in TilesIslet.
A Swing is in TilesIslet.
East of TilesIslet is An Odd Low Woodland. West of An Odd Low Woodland is nowhere.
Instead of going east from TilesIslet, block conditional exits.
This was tested with my trizbort files for Shuffling Around (26 rooms) and Roiling Original (84). It compiled in the IDE.

#221 Inform 7 export now by-region/room

---

AppSettingsDialog.Designer.cs
AppSettingsDialog.cs
Settings.cs

There's some tricky stuff in here. Shifting Reset() was not done lightly. Since that code is hit more often, I want to detail it first.
I also think it's named too vaguely. Maybe ResetProjectToApp() is more accurate? (This is obviously low priority, but I got tripped up.)
ResetApplicationSettings();
LoadApplicationSettings();
Reset();
At any rate, if it is before, then the first project you open gets Microsoft Sans Serif font with the new code. Before, it would go to Comic Sans. Otherwise, it works well. Reset changes nothing else that ResetApp... and LoadApp... change.
In fact I think this will help fix the behavior I saw with specifying margins by default in new apps.
So Reset() looks like it should be first because it is a more general name, but if/as we move to having more default app …

#212 change default font and allow option

---

Settings.cs

I'd still like if we could grey out the margins if "Document-Specific Margins" is unchecked, but I'm not sure how to do that.

#207 plus delete a stray static bool

---

SettingsDialog.Designer.cs
SettingsDialog.cs

In some code I cut and pasted earlier from something with a tooltip, I deleted the tooltip but didn't delete the cursor. So I threw that change in too.
Code change is in 2 places in SettingsDialog.cs since we need to check for if we should grey out the margin fields initially.

#230 fix plus remove wrong cursor over checkbox

---

Settings.cs
SettingsDialog.Designer.cs

If I opened 1594, then 1593, then 1594, the default font disappeared. It now defaults to Arial in such a case.
Also I lined up a few other texts. This is all cosmetic, so I hope that's ok to dump into the one pull.

minor gui changes

---

Export/CodeExporter.cs
Export/Inform6Exporter.cs

deaccent seems like a good general function if we want to fix things for other languages (and I think we do) so I put it in CodeExporter.cs. Basically, generateur without the accents is acceptable and preferred for the parser. So we want to account for that.
stripunaccentedcharacters is less aggressive than the original stripoddcharacters, as it would be nice to allow for as many foreign languages as possible.
I tested this with diesel.trizbort which is here: https://gist.github.com/andrewschultz/e3b7577b8eb26fa436d8
The exported file now matches Hugo's suggestions.
As I sent in this pull request I realized there's still a question of what to do with the ß character for German. So I may be adding a small push to that e.g.
if (c == 'ß') x = x + "ss"

#234 i6 special character name export

---

AppSettingsDialog.Designer.cs
AppSettingsDialog.cs
Canvas.cs
Drawing.cs
Settings.cs
SettingsDialog.Designer.cs
SettingsDialog.cs

I needed to rearrange the gui (again) & unfortunately there was no way around combining that with adding the code.
I renamed some variables so that we would not get confused. Maybe we should create
Settings.Global.(whichever)
Settings.Local.(whichever) ? I suspect you were thinking along these lines.
Ideally I should have arranged the gui for one pull request then dropped in the hand-drawn feature, but I got the order of things wrong and had the XML, etc., implemented first..
So now we now have the option to set hand-drawn as a default for a new project whichever way we please. I turned it off as I suspect that is people's preference, and that meant updating a tooltip.

#245 added global hand-drawn feature

---

Settings.cs

For some reason project.current.author gets assigned by default to null but dialog.author does not.
The solution is just to assign the metadata to "" and thus when trizbort compares, it's the empty string vs the empty string instead of null vs the empty string.
I checked where these strings were used. They are used in export and we always check for isNullOrWhiteSpace (and we should, in case the user mistakenly leaves a space in there.)
For testing i checked saving documents with various fields blank. They looked the same before and after the change.

#246 initialize author/title/etc to empty string

---

MainForm.cs
Settings.cs

This should be pretty straightforward. Code was cut/pasted and changed from TADS to Zil, but the programmer missed a case.
I tacked on a LastExportHugoFileName to the XML as it looks like I forgot to put that in there when I originally wrote the Hugo exporter module.

#251 last zil filename now exported

---

Export/CodeExporter.cs

With the new bracketed text to determine person/scenery etc., I needed to account for, er, if someone didn't use brackets at all. Now I did.

Fix when false errors show up in I7 export

---

Export/AlanExporter.cs
MainForm.Designer.cs
MainForm.cs
Settings.cs
Trizbort.csproj

This is sort of a fun project inspired by a friend who's always been encouraging to me, but it also helped me check work with the new properties in brackets.
I created AlanExporter.cs by copying Inform7Exporter.cs and going through line by line.
The manual is here: http://www.alanif.se/downloads/documentation/manual.pdf
Note that I also added in Hugo menu item grey-out if there were no rooms. This is something I forgot to do with Hugo export. I don't know if it's worthwhile to write a checklist for a new language since you want to do templates. But I basically just searched for the TADS functions and menu items and checked off they were there for ALAN.

Alan export (#65)

---

Room.cs

This code just seems like a fancy way of tacking on an extra carriage return we don't need. But I'm wondering if Genstein was trying to do something I wasn't aware of.
I think it looks neater without the carriage return, and it would be most flexible to allow the user to define custom offsets from the 8 basic positions, if they want.
I don't like the idea of forcing an extra carriage return as Genstein's code does, because the user can put one in if they want, if they need the spacing.

fix extra spacing in n/ne/nw item lists

---

Properties/Resources.resx

Basically we just need to make sure file/directory names are capitalized correctly so Linux builders don't bail on this file. I checked Trizbort still builds on Windows after these changes.

Resources.resx case changes for Linux building

---

MapStatistics.cs
UI/MapStatisticsView.cs

What the summary says. I don't think there's much that could regress here, but we wrote the stat routine before adding the end room. Tested on trizbort maps with and without end rooms.

end room now appears in stats

---

MapStatistics.cs
UI/MapStatisticsView.cs

added door/connection stats. None of the really esoteric stats I talked about in #342.
The plur function simply tacks on an s if an integer isn't 1, to make a number plural e.g. 0 door(s). It might be useful other places if more stats are added.
I just did some odd stuff with push I'd never done before, so I hope nothing odd happens with this pull, but if it does, let me know.

door and connection changes

---

UI/Controls/Canvas.cs

Genstein's code basically just ran several zooms (5/4 factor) til it worked. This appears to be more accurate.
If we want, we can tack on (document-specific) margins to the (left-right)and (top-bottom) calculations. But I think this is a lot cleaner.
I just noticed I probably threw too many (float)'s in there. Is there any utility or option in Visual C# that is a good code format checker? It'd be neat to be able to do this, like PyCharm does for Python.

initial room zoom is now accurate to nearest percent

---

MapStatistics.cs

Sorry about the aborted pull request. I forgot to save the file before committing/pushing & so one line was in the wrong place.
This fixes the crashes but doesn't fix the issue with the "bent connections" name. If you think of a good name, let me know.
Values default to 0 (north) for null ports in the diagonalConnections function, which means we return a 0 in the diagonal count.
Either port being null means a connection can't be bent since there is no room to go to.

check for null ports in diagonal/bent (correct source this time)

---

testing/font-all.pl
testing/testsync.pl

I found a small bug with variable name capitalization in the process. My experiences on stackoverflow have convinced me it's a good idea to use these for any script over 10 lines.

use strict/warnings added to PERL test files

---

testing/vtest.py

I hope python scripts are okay in addition to perl scripts. If not, let me know.
This tests the file vs app code that was merged into the code by creating files with various version headers (2.5.9.9, 0.5.9.9, 1.6.9.9, 1.4.9.9, etc.) and opening them in Trizbort and then deleting them.
And while I'm guessing it's ok for me to merge these sort of things automatically, let me know if it isn't.

python script to test version warning checks

---

MapStatistics.cs
testing/roomstats-dangling-connections.trizbort
testing/roomstats-dead-ends.trizbort
testing/roomstats-startroom-dead-end.trizbort
testing/roomstats.bat

We had the brackets wrong in a nested if statement, and that caused Trizbort to miscount dead ends in general.
Once that was fixed, it uncovered another bug where Trizbort counted floating rooms with dangling connectors as dead ends.
The test files test these cases.

Dead end stat fix

---

UI/Controls/Canvas.cs

Trivial fix. Tested with two small files 1) containing no end rooms/start rooms 2) containing both.

GUI fix for mult room highlight/rt click

---

UI/MapStatisticsView.cs

2 lines for width/height with margins and without. Tested with some of my own files.

added width/height to map statistics

---

Room.cs

causes exception when opening room dialog and rooms shapes could be changed without meaning too.

fix (rooms) - room shapes were calculated incorrectly - Fixes #394

---

Domain/AppSettings/ApplicationSettings.cs
Domain/AppSettings/ApplicationSettingsController.cs
Domain/Controllers/CopyController.cs
Trizbort.csproj
UI/Controls/Canvas.cs
UI/MainForm.cs
Util/ClipboardHelper.cs

The recently open maps list was not working since we moved the settings
to a JSON format.  Made it so this worked again and opened it up to
add some configuration for this section in the future.

fix (settings): fix recently opened files list in menu

---

UI/MainForm.cs

last opened project was being set even if it was an invalid
map file that loaded unsuccessfully.

fixes #442

---

Domain/AppSettings/ApplicationSettings.cs
Domain/Elements/Room.cs
Domain/Misc/TextBlock.cs
Setup/Settings.cs
UI/Controls/Canvas.cs
UI/Controls/TrizbortToolTip.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs

This is my solution proposition for #459 
The tooltip is being re-drawn when it is shown upon panning and moving the element. This causes a rather noticeable tooltip flicker, especially when snap-to-grid is turned off or when panning.
Known "issues":
1. flicker
2. when moving the element or panning in a way that the element is not visible on the canvas, the tooltip "stays" near the visible edge

Solution for #459

---

Domain/Elements/Room.cs
UI/RoomPropertiesDialog.cs

This patch corrects a problem in the serialization/de-serialization of the `Room` state which was causing the `handDrawn` setting to be inverted by the save and load process.
Additionally the "Hand Drawn Edges" option is now disabled when setting the line drawing style to anything other than "Straight Edges" from the room properties dialog to better inform the user where the option is supported.

Fix issues with handling of "Hand Drawn Edges" setting.

---

Export/Languages/Inform6Exporter.cs

- there should be a comma between "name" and "description"
- if the Trizbort location/object has a dash in it, it has to be removed

Inform 6 export: fixing 2 bugs leading to compiler errors

---

Export/Languages/Inform6Exporter.cs

C# isn't my first or second language. Which is to say I didn't know what I was doing on many different levels (including perhaps the interpretation of all the "Thing" properties).
This might not be "production-ready" code, still I'd wanted to publish this.

Support more Inform6 attributes

---

Export/Languages/Inform7Exporter.cs

If the region is a reserved word, any rooms would be disconnected from that region (which would have a new name assigned during export)

I7 Export - Region name is reserved word, room not assigned
