JasonLautzenheiser/trizbort

Docs/index.shtml
Docs/style.css

I'm considering a new style for keyboard shortcuts.
I also believe I messed up the order in the ToC vs. the order in the actual document. I need to write a script to figure that out, but that will be for the next pull request, as once I have the script, I may want to reorganize more.

Valid HTML, new style for menu items

---

.gitignore
Docs/index.shtml
Docs/style.css

I hope my addition to the .gitignore file is noncontroversial, but I'd like to check all the same. I run .pl files on index.shtml to make sure of formatting & we don't need to expose those.

more formatting, added .gitignore for .pl files in docs

---

MapStatistics.cs
MapStatisticsView.cs

Compiled and tested this trivial feature. Thanks for letting me sneak it in.

Adding map stats (#167)

---

AppSettingsDialog.Designer.cs
AppSettingsDialog.cs
DisambiguateRoomsDialog.Designer.cs
Export/TadsExporter.cs
Settings.cs

182 should be trivial but you never know.
185, I compiled a Tads3 project and an adv3lite project to make sure it works, using a simple map with 2 regions. I edited the files by hand to get the GUI to work but flipped through everything to test.

#182 and #185

---

AppSettingsDialog.Designer.cs
AppSettingsDialog.cs
Canvas.cs
Connection.cs
Room.cs
Settings.cs

1) With this commit, trizbort can now support margins if we check the appropriate box. I put it in app settings but maybe it should go in map settings
2) (ctrl) - (left/right bracket) now lets you rotate. Right now, which room supports ctrl is a bit arbitrary (lower ID) but I think/hope the interface is easy enough people can fix it. And yes, I can follow up with another fix. This one was sitting too long.
I think more importantly I made it so you could skip over occupied ports in (2). If you think this should be an app setting flag, I can implement that.
I'm also generally worried about the coding for (1) as I don't have full VS 2015 to edit the GUI, so it may not look right. And for (2) I had to define something private as public. I'm not sure of the security implications.
Kick back …

A pull request that adds a feature and an issue

---

MainForm.Designer.cs
MainForm.cs
MapStatisticsView.cs

After poking at this, it seems like the fix basically works. We can now pipe to a popup or to a file. If we cannot open (file name).log, we open something in the temp dir. Error checking is installed as well.

Very initial fix for #100

---

MainForm.cs
Project.cs
Settings.cs

This is not a huge fix, but I've stumbled over what "reset" means enough. I think the function name should be clearer.
General sanity-check testing done, reloading a file, making a new file etc.

reset function now has better name

---

Room.cs
RoomPropertiesDialog.cs

This looks like a careless typo on my part. I also added code to stop the dirty flag from being set in one case when it shouldn't.

Issue #240 regression/exception

---

Export/Inform6Exporter.cs
testing/region-accent-clash.trizbort
testing/region-accent-one.trizbort

Source code to create regions in I6 re: Hugo Labrande's suggestions.
https://gist.github.com/andrewschultz/49684091e813f094c530 has the trizbort file and before and expected after.
I suspect this will cause a merge conflict with 234 as they are changing the same line of code. But they are different enough functionality they should have a new pull request.
Line (64 before/73 after) is the one in question.

Issue 233 i6 regions

---

Domain/CommandLineOptions.cs
Export/AlanExporter.cs
MainForm.cs

Added code export commandline parameters

---

Project.cs
Room.cs
Settings.cs

Just needed a few initializations and a typo fix.

fixed erroneous duplicate start/end room warning popups

---

Export/Inform6Exporter.cs

Forgot to save the C# file in visual studio after debugging, before committing.
The line endings seem messed up so if there is a way I can/should fix that, let me know and I'll resend it.

2nd try at pull request

---

UI/Controls/Canvas.cs

Reverts JasonLautzenheiser/trizbort#340

Revert "initial room zoom is now accurate to nearest percent"

---

MapStatistics.cs
UI/MapStatisticsView.cs

I'm convinced this can be cleaned up, especially the string-joining but I hope/think none of what I've included is useless. It's all stuff I've wanted to know for my medium to large size games.
I'm also convinced things can be organized better, but I hope the current information dump is interesting to some people.
If I've made big coding mistakes, kick it back to me and tell me what I need to clean up. I've checked with my usual big files, but things get overlooked.

Detailed stats of various use

---

MapStatistics.cs
UI/MapStatisticsView.cs

The room shape detection code seemed pretty straightforward.
I lumped the ifs in MapStatisticsView into an "else" due to very minor formatting issues.

Implemented #355

---

MapStatistics.cs
UI/MapStatisticsView.cs
testing/roomstats-case-insensitive-duplicate-testing.trizbort
testing/roomstats-duplicate-testing.trizbort

The two test files check 1) general duplicate cases and 2) case insensitivity.

Duplicate rooms in stats #354

---

Domain/AppSettings/ApplicationSettings.cs
Domain/AppSettings/ApplicationSettingsController.cs
Domain/Connection.cs
Export/TadsExporter.cs
Room.cs
Settings.cs
Trizbort.csproj
UI/AutomapDialog.cs
UI/Controls/Canvas.cs
UI/MainForm.cs
UI/NewVersionDialog.cs

appsettings are refactored out of the main settings class. Settings now stored in appsettings.json in application folder. Will read in legacy settings.

Application Settings refactor

---

UI/SettingsDialog.Designer.cs
UI/SettingsDialog.resx

fix (UI) - add scrollbars to map settings description and history.

---

Domain/AppSettings/ApplicationSettings.cs
Domain/AppSettings/ApplicationSettingsController.cs
UI/AppSettingsDialog.Designer.cs
UI/AppSettingsDialog.cs
UI/MainForm.cs

change (settings) - App settings are now saved when settings dialog is closed on OK

feat (settings) - Added option to show full file path in title bar

---

Room.cs
Settings.cs
UI/RoomPropertiesDialog.Designer.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs
UI/SettingsDialog.resx

feat (rooms) - Can now set a default room shape in Map Settings

---

Room.cs
UI/Controls/Canvas.cs
UI/RoomPropertiesDialog.Designer.cs
UI/RoomPropertiesDialog.cs

This feature allows the user to link a room to a different room on the map.
This allows for virtual links to help keep a clean map from crazy connections.
Fixes #370

feat (map) - Added ability to link one room to another

---

Automap/Automap.cs
Domain/Controllers/CopyController.cs
Domain/Elements/Connection.cs
Domain/Elements/Room.cs
Domain/Misc/Colors.cs
Domain/Misc/Palette.cs
Export/QuestExporter.cs
Setup/Settings.cs
UI/Controls/Canvas.cs
UI/RoomPropertiesDialog.Designer.cs
UI/RoomPropertiesDialog.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs

feat (room): add ability change the subtitle text/font at map level
fix (settings): fix double msgbox on default room name
fix (settings): removed the "largeText"-name default setting as it's controlled by regions
feat (room): allow subtitle color to be set on room level
fix (room): fix cancel color dialog setting color when it shouldn't

Set subtitle colors

---

Domain/Misc/Numeric.cs
UI/MainForm.cs

clamp the zoom value to fit within the constraints

---

Domain/StatusBar/CapsLockStatusWidget.cs
Domain/StatusBar/IStatusWidget.cs
Domain/StatusBar/NumLockStatusWidget.cs
Domain/StatusBar/Status.cs
Domain/StatusBar/ZoomStatusWidget.cs
Trizbort.csproj
UI/MainForm.cs
Util/KeyboardHelper.cs
app.config

cleaned up zoom statusbar widget
added caps lock and num lock statusbar widget

refactored toolbar to make more extensible

---

Domain/AppSettings/ApplicationSettings.cs
Domain/Elements/Room.cs
Domain/Misc/TextBlock.cs
Setup/Settings.cs
UI/Controls/Canvas.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs

This is my solution proposition for #456 
Please let me know if changes are needed prior to pull.

Solution for #456

---

Domain/AppSettings/ApplicationSettings.cs
Domain/Elements/Room.cs
Domain/Misc/TextBlock.cs
Setup/Settings.cs
UI/Controls/Canvas.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs

This is my solution proposition for #455 
If the user was Panning prior to releasing the mouse button, the context menu will not be displayed.

Solution for #455

---

Domain/AppSettings/ApplicationSettings.cs
Domain/AppSettings/ApplicationSettingsController.cs
Domain/Controllers/CopyController.cs
Domain/Elements/Connection.cs
Domain/Elements/Room.cs
Domain/Misc/TextBlock.cs
Setup/Settings.cs
UI/Controls/Canvas.cs
UI/MainForm.Designer.cs
UI/MainForm.cs
UI/SettingsDialog.Designer.cs
UI/SettingsDialog.cs

Solution propositions for various minor issues.
What is worth consideration:
1. Recent Files list length could be configurable in the app settings, instead of having a hardcoded 4
2. Adding Paint/Repaint methods in the Room class
3. There is one more place where `ApplicationSettingsController.AppSettings.RecentProjects` is using `.Add` instead of `.Insert`

Solutions for #387, #452, #454, #460

---

UI/MapStatisticsView.cs

fix spelling on statistics page

---

Domain/AppSettings/ApplicationSettings.cs
Domain/AppSettings/ApplicationSettingsController.cs
Domain/Elements/Connection.cs
Domain/Elements/Room.cs
UI/AppSettingsDialog.Designer.cs
UI/AppSettingsDialog.cs
UI/Controls/Canvas.cs

create settings to limit number of characters in tooltip descriptions of
rooms and connections

create settings to show/hide tooltips

---

Domain/AppSettings/ApplicationSettings.cs
Export/Languages/AdventuronExporter.cs
Trizbort.csproj
UI/MainForm.Designer.cs
UI/MainForm.cs

Hello,
You may remember I've had an "import from Trizbort" feature in Adventuron for a while (you blogged about it), but I thought it would be convenient to have an exporter in Trizbort too.
It's only basic, but it should work for basic maps (hopefully).
Chris

Added Simple Exporter for Adventuron Text Adventure Creation System

---

Domain/Controllers/CopyController.cs
Trizbort.Tests/StringExentensionTests.cs
Trizbort.Tests/Trizbort.Tests.csproj
Trizbort.Tests/packages.config
Trizbort.sln

Also added in the test project which seemed to have been removed.

Add ReferenceID to the properties copied on a room

---

UI/MainForm.Designer.cs

Ctrl+Comma for Map Settings
Alt-Shift-S for App Settings

Add shortcuts to app and map settings forms

---

Trizbort.Tests/Trizbort.Tests.csproj
Trizbort.Tests/packages.config
Trizbort.csproj
Trizbort.sln
packages.config

removed test project, will revamp this as code is refactored to be more testable

Update some dependencies and remove test project

---

.editorconfig
Export/CodeExporter.cs
Export/Domain/Thing.cs
Export/Languages/Inform6Exporter.cs
Extensions/StringExtensions.cs
Trizbort.csproj

Fixed the gender stuff to only apply to animate objects
Added the PartOf attribute to set the transparent attribute (which is how
I6 handles this - #499)
some minor code cleanup and refactoring

I6 Export Updates

---

.gitignore
Domain/StatusBar/ZoomStatusWidget.cs
Program.cs
Trizbort.csproj
Trizbort.sln
appsettings.json
packages.config

Reverts JasonLautzenheiser/trizbort#536

Revert "update project to .net 6"

---

Properties/AssemblyInfo.cs
UI/Controls/Canvas.Designer.cs

 fix menu image scaling on context menu
